Homework 4
DrawGun/th_react_shop pull request #4
Opened 2018-08-16 14:19 UTC by DrawGun

2018-08-21 11:45 UTC, index01d requested changes

2018-08-21 11:45 UTC, index01d commented on src/App.js
> +class App extends Component {
стоило бы отделить контейнер корзины от компонента приложения

2018-08-21 11:45 UTC, index01d commented on src/components/basket/Basket.js
> +                        pathname: rootPath,
для унификации всегда было бы лучше если бы path-Helper'ы были функциями (пусть и без параметров)

2018-08-21 11:45 UTC, index01d commented on src/components/layouts/Header.js
> +          <Collapse isOpen={this.state.isOpen} navbar>
лучше выделять отдельный компонент меню

2018-08-21 11:50 UTC, DrawGun commented on src/App.js
> +class App extends Component {
@index01d не совсем понял, что имелось в виду. Можно, пожалуйста, немного пояснить? Может я неправильно понял логику `createContext`

2018-08-21 11:51 UTC, DrawGun commented on src/components/basket/Basket.js
> +                        pathname: rootPath,
согласен, боялся, что к этому придерутся как раз, так и произошло, только наоборот ) спасибо, поправлю

2018-08-21 11:51 UTC, DrawGun commented on src/components/layouts/Header.js
> +          <Collapse isOpen={this.state.isOpen} navbar>
ok, сделаю

2018-08-21 13:28 UTC, index01d commented on src/App.js
> +class App extends Component {
имеется ввиду создать отдельный компонент CartContainer и обернуть в него приложение в функции render компонента App.

2018-08-21 17:17 UTC, DrawGun commented on src/components/layouts/Header.js
> +          <Collapse isOpen={this.state.isOpen} navbar>
готово

2018-08-21 17:17 UTC, DrawGun commented on src/components/basket/Basket.js
> +                        pathname: rootPath,
готово

2018-08-21 17:17 UTC, DrawGun commented on src/App.js
> +class App extends Component {
не совсем понял зачем это надо но сделаю

2018-08-22 20:56 UTC, index01d requested changes

2018-08-22 20:56 UTC, index01d commented on src/components/layouts/AppSwitch.js
> +            <RouteWithSubRoutes key={i} {...route} />
Здесь получается ты создаешь элементы компонента RouteWithSubroutes, а не Route, как ожидает Switch для работоспособности. Если поменять на простой вызов функции RouteWithSubroutes
```
{routes.map((route, i) => (
         RouteWithSubRoutes(route, i)
))}
```
то в результате Switch получит именно элементы компонента Route, который вернет ему данная функция и все отработает хорошо

P.S: отловить было непросто, но вот как я это сделал: отписал лог в каждом render-методе всех компонентов по дереву и отловил, что не происходит вызова render RouteWithSubroutes.

2018-08-22 21:42 UTC, DrawGun commented on src/components/layouts/AppSwitch.js
> +            <RouteWithSubRoutes key={i} {...route} />
@index01d а не влияет при это расположение списка роутов?
такое впечатление, что перестал работать `exact: true` к примеру url `http://localhost:1234/productisxxx/2` отдает главную страницу а должен был отдавать страницу 404, но если поменять код наоборот и проверку на 404 делать раньше, то все работает

```
      <MainLayout>
        <Switch location={isModal ? this.previousLocation : location}>
          <Route component={NoMatch} />  <-----
          
          {routes.map((route, i) => (
            RouteWithSubRoutes(route, i)
          ))}
        </Switch>

        {isModal ? <Route path={basketPath} component={BasketModal} /> : null}
      </MainLayout>
```

есть ли какое-нибудь соглашение по этому поводу?

2018-08-23 06:46 UTC, index01d approved these changes

2018-08-23 06:46 UTC, index01d commented on src/routes/Products.js
> +  path: rootPath,
для унификации нужно оставить функцией ;)

2018-08-23 07:11 UTC, DrawGun commented on src/routes/Products.js
> +  path: rootPath,
какой-то конфликт, видимо

2018-08-23 08:58 UTC, merged