homework_5
DrawGun/th_react_shop pull request #5
Opened 2018-09-04 23:50 UTC by DrawGun

2018-09-05 01:45 UTC, index01d requested changes

2018-09-05 01:45 UTC, index01d commented on src/components/gallery/Gallery.js
> +  changeActiveIndex(type) {
с тз читабельности и тестерабельности гораздо круче, когда сигнатура используемого метода объясняет высокоуровневую семантику, а не низкоуровневую реализацию (например: goBack(), goNext(), с использованием _changeActiveIndex)

2018-09-05 01:45 UTC, index01d commented on src/components/gallery/Gallery.js
> +    const images_length = images.length;
?

2018-09-05 01:45 UTC, index01d commented on src/components/gallery/GalleryModal.js
> +import { API_V1_PATH, API_PRODUCTS_PATH, API_GALLERY_PATH } from './../../helpers/routes/api';
все ж такие лучше использовать алиас ~ для импорта. относительные пути усложняют жизнь
`import { API_V1_PATH, API_PRODUCTS_PATH, API_GALLERY_PATH } from '~/src/helpers/routes/api'`

2018-09-05 01:45 UTC, index01d commented on src/components/gallery/GalleryModal.js
> +  componentDidMount() {
по-хорошему логика загрузки картинок дб выделена в контейнер, отдельно от презентационного кода модалки

2018-09-05 01:45 UTC, index01d commented on src/components/layouts/AppSwitch.js
> +            <Fragment>
сделать роут для всех модалок не требовалось:) некоторые модалки и без роута могли бы обойтись

2018-09-05 01:45 UTC, index01d commented on src/components/layouts/AppSwitch.js
> +            <Fragment>
но пусть)

2018-09-05 01:45 UTC, index01d commented on src/components/layouts/MainLayout.js
> +    <Header match={match} />
чтобы не передавать match по иерархии, следует использовать HOC withRoutes из react-router https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md

2018-09-05 01:45 UTC, index01d commented on src/containers/GalleryContainer.js
> +      <Row className='mb-2 mt-5'>
презентационный row попал в контейнерный компонент, такое себе :)

2018-09-05 01:45 UTC, index01d commented on src/containers/ImageContainer.js
> +  fetchImage() {
из-за отстуствия чисто-контейнерного компонента я вижу эту реализацию уже не в первый раз

2018-09-05 01:45 UTC, index01d commented on src/containers/ImageContainer.js
> +      <Container>
перемешивание презентационной и контейнерной логики привело к дублированию контейнерного кода. нужно исправить

2018-09-05 01:45 UTC, index01d commented on src/helpers/parser.js
> +class JSONAPI {
адовый класс:) я так понимаю он скопирован?

2018-09-05 11:46 UTC, DrawGun commented on src/components/gallery/Gallery.js
> +  changeActiveIndex(type) {
поправил

2018-09-05 11:46 UTC, DrawGun commented on src/components/gallery/Gallery.js
> +    const images_length = images.length;
да, косяк поправил и раиспользовал в новой логике, спасибо

2018-09-05 11:47 UTC, DrawGun commented on src/components/layouts/AppSwitch.js
> +            <Fragment>
хотел свести все к одной кнопке и не придумал ничего лучшего

2018-09-05 12:04 UTC, DrawGun commented on src/components/gallery/GalleryModal.js
> +import { API_V1_PATH, API_PRODUCTS_PATH, API_GALLERY_PATH } from './../../helpers/routes/api';
поправил

2018-09-05 12:08 UTC, DrawGun commented on src/components/layouts/MainLayout.js
> +    <Header match={match} />
точно, забыл )
этот рудимент не используется, я использую проверку [`matchPath`](https://github.com/DrawGun/th_react_shop/pull/5/files#diff-37452838612cbbc2cafc47643720304bR27) для проверки на какой странице я нахожусь. насколько оправдано использование этого метода?

2018-09-05 12:09 UTC, DrawGun commented on src/helpers/parser.js
> +class JSONAPI {
да, конечно )
Искал взаимодействие react и json api и ничего хорошего не нашел, может есть какой-нибудь стандарт на эту тему?

2018-09-05 12:23 UTC, DrawGun commented on src/components/gallery/GalleryModal.js
> +  componentDidMount() {
ага, спасибо, не заметил, свел все к GalleryContainer

2018-09-05 12:25 UTC, DrawGun commented on src/containers/GalleryContainer.js
> +      <Row className='mb-2 mt-5'>
согласен, спешил, поправлю

2018-09-05 12:26 UTC, DrawGun commented on src/containers/ImageContainer.js
> +  fetchImage() {
это другой запрос, 
просто пытаемся найти картинку по ID это реализация последнего задания со звездочкой,
думаю, что тут все в порядке

2018-09-05 12:26 UTC, DrawGun commented on src/containers/ImageContainer.js
> +      <Container>
поправил

2018-09-06 10:02 UTC, index01d commented on src/components/layouts/MainLayout.js
> +    <Header match={match} />
поидее можно получить состояние матчинга из свойства match, которое передает роут

2018-09-06 10:05 UTC, index01d commented on src/containers/ImageContainer.js
> +  fetchImage() {
не отменяет необходимости отделить контейнер :)

2018-09-06 10:07 UTC, index01d commented on src/helpers/parser.js
> +class JSONAPI {
подсказать вряд ли что-то могу, но могу заметить, что react непричем, лучше просто гуглить на предмет json api и js

2018-09-06 12:04 UTC, DrawGun commented on src/components/layouts/MainLayout.js
> +    <Header match={match} />
мне показался вариант с `matchPath` более явным

2018-09-06 12:05 UTC, DrawGun commented on src/containers/ImageContainer.js
> +  fetchImage() {
вынес контейнерную логику в компонент контейнер

2018-09-07 19:35 UTC, merged