Homework 8
DrawGun/th_react_shop pull request #7
Opened 2018-09-19 13:56 UTC by DrawGun

2018-09-19 14:03 UTC, DrawGun commented on src/middleware/API.js
>    if (payload)
в этом месте почему-то сбрасывается параметр `method` и запрос идет как `Request Method: OPTIONS`.
если закомментировать строчку и не передавать `payload`, то запрос будет иметь `Request Method: POST`

2018-09-20 13:14 UTC, index01d requested changes

2018-09-20 13:14 UTC, index01d commented on src/components/elements/Pagination.js
> +                  <PaginationLink onClick={() => fetchProducts(stepByCount)}>
здесь лучше делать history.push с указанием в query номера страницы

2018-09-20 13:14 UTC, index01d commented on src/components/elements/Pagination.js
> +                  <PaginationLink onClick={() => fetchProducts(stepByCount)}>
это же правило касается любых фильтров, иначе синхронизация с адресной строки резко станет сложной задачей.

2018-09-20 13:14 UTC, index01d commented on src/components/products/Catalog.js
> +      fetchProducts({});
дб в prepareData

2018-09-20 13:44 UTC, DrawGun commented on src/middleware/API.js
>    if (payload)
добавление CORS разрешило ситуацию

2018-09-20 13:45 UTC, DrawGun commented on src/components/products/Catalog.js
> +      fetchProducts({});
@index01d не понял комментария, поясни, плиз

2018-09-21 13:38 UTC, index01d commented on src/components/products/Catalog.js
> +      fetchProducts({});
ошибся номером задания:) prepareData еще рано.

2018-09-21 13:39 UTC, index01d approved these changes

2018-09-22 14:49 UTC, merged